const config = {
  SITE_TITLE: process.env.REACT_APP_SITE_TITLE,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  SITE_KEY: process.env.REACT_APP_SITE_KEY,
  RECAPTCHA_V3_SITE_KEY: process.env.REACT_APP_RECAPTCHA_V3_SITE_KEY,
  APP_TYPE: process.env.REACT_APP_TYPE,
  SOCKET_API_ENDPOINT: process.env.REACT_APP_SOCKET_API_ENDPOINT,
  AUTHORIZE_API_MODE: process.env.REACT_APP_AUTHORIZE_API_MODE,
  AUTHORIZE_CLIENT_KEY: process.env.REACT_APP_AUTHORIZE_CLIENT_KEY,
  AUTHORIZE_API_LOGIN_ID: process.env.REACT_APP_AUTHORIZE_API_LOGIN_ID,
  REACT_APP_GOOGLE_API_KEY: process.env.REACT_APP_GOOGLE_API_KEY,
  REACT_APP_KLIPPA_AUTH_KEY: process.env.REACT_APP_KLIPPA_AUTH_KEY,
};
export default config;