export interface ThemeSetting {
  id: number;
  label: string;
  property: string;
  value: string;
  status: number;
  eventUrl: string;
  createdAt: string;
  updatedAt: string;
}

export interface Page {
  id: number;
  title: string;
  slug: string;
  body: string | null;
  isPublished: number;
  createdAt: string | null;
  updatedAt: string;
  eventUrl: string;
  buttonLabel: string | null;
  pageType: number | null;
  url: string | null;
}

export interface ShowMainTab {
  biddingTab: boolean;
  donationTab: boolean;
  salesItemTab: boolean;
  pages: Page[];
}

export interface Sponsor {
  id: number;
  name: string;
  photo: string | null;
  description: string | null;
  type: string | null;
  url: string | null;
  order: number;
  eventUrl: string;
  isShowAtHome: number;
  isShowAtDonationPresentation: number;
  isShowAtAuction: number;
  isShowAtTicketing: number;
  sponsorid: number;
  contactId: number | null;
  transactionId: number | null;
  atItemId: number | null;
  ticketId: number | null;
  createdAt: string;
  updatedAt: string;
}

// Main setting type jo bahut bada hai
export interface EventSetting {
  id: number;
  name: string;
  endDate: string;
  startDate: string;
  status: string;
  sponsorCount: number;
  isShowSponsorInFooter: boolean;
  logourl: string;
  ticketPurchaseUrl: string;
  wifi: string;
  password: string;
  closed: number;
  timezone: string;
  hasBuyNowButton: boolean;
  organizationBanner: string;
  technologySponsor: string;
  technologySponsorType: string;
  customerMode: number;
  productMode: number;
  hasRequiredRegistration: boolean;
  footerLogo: string;
  footerBgColor: string;
  bodyBgColor: string;
  mobileEventBanner: string;
  desktopEventBanner: string;
  footerDesc: string;
  authorizeApiLoginID: string;
  authorizeMode: string;
  authorizeClientKey: string;
  sponsorPositionOnDesktop: string;
  sponsorAtPositionOnDesktop: number;
  sponsorMessageOnDesktop: string;
  bannerWidth: number;
  bannerHeight: number;
  sponsorMessage: string;
  creditCardFeeDisclosure: string;
  creditCardFeeAmount: string;
  homePageHtml: string;
  homePageCss: string | null;
  hasRequiredCreditCard: boolean;
  ccReqDuringReg: boolean;
  homeRoute: string;
  globalCustomCSS: string;
  donationTitle: string;
  technologySponsorUrl: string;
  donationDescription: string;
  donationPhoto: string | null;
  donationVideo: string;
  askEmailDuringReg: boolean;
  askAddressDuringReg: boolean | null;
  emailRequired: boolean;
  addressRequired: boolean | null;
  appAssignsBidNumber: boolean;
  ccRequiredOnBid: boolean;
  thermometerGoal: string;
  thermometerType: string;
  creditCardFeeName: string | null;
  silenceAllTexts: boolean;
  cardsCharged: boolean;
  creditCardFeeAppliesTo: number;
  taxId: string;
  eventUrl: string;
  organizationName: string;
  contactPhone: string;
  contactEmail: string;
  taxStatus: string;
  organizationLogo: string;
  twilioMobile: string | null;
  siteDeactivate: boolean;
  organizationId: number;
  siteWelcomeMsg: string;
  isEventTicketing: boolean;
  liveTabActive: boolean;
  activeLiveEvent: boolean;
  streamingSource: string | null;
  embedCode: string;
  chatEmbedCode: string;
  chatBoxActive: boolean;
  regCustomFields: string;
  statementComment: string;
  isHideAuctionTab: boolean;
  isHideDonationsTab: boolean;
  isHideItemSalesTab: boolean;
  allowRegistration: number;
  adminTwoFactorAuth: boolean | null;
  isAcceptDonationAtRegistration: boolean | null;
  isAllowRecurring: boolean;
  isIncRevenueFromTicketing: boolean;
  isAssignBidNumbers: boolean;
  auctionSponsorMessage: string;
  donationPresSponsorMessage: string;
  ticketingSponsorMessage: string;
  isAllowRegisterToGuestAtTicket: boolean;
  address: string;
  city: string;
  state: string;
  zip: string;
  isOpenEventSiteForTicketing: boolean;
  donationsTab: string;
  itemSalesTab: string;
  hasReservationTicket: boolean;
  hasSponsorshipsTicket: boolean;
  isLiveAllDonation: boolean;
  isTeamGiving: boolean | null;
  teamGivingMedia: string;
  teamGivingText: string;
  reqName: number;
  reqPhone: number;
  reqEmail: number;
  reqAdd: number;
  livedate: string;
  isDisplayActionTimes: boolean;
  website: string;
  facebook: string;
  instagram: string;
  twitter: string;
  isCustomeCss: boolean;
  script: string | null;
  teamGivingHeader: string;
  startBidPercent: number;
  bidRaisePercent: number;
  buyNowPercent: number;
  checkInZipRequired: boolean | null;
  domain: number;
  isLoggable: boolean;
  isGolf: boolean;
  source_code: string | null;
  useFormalTitles: boolean;
  teamGivingUrl: string | null;
  notifyOnDonate: boolean | null;
  notifyOnSale: boolean | null;
  notifyOnPayment: boolean | null;
  notifyOnBuy: boolean | null;
  notifyOnPurchase: number;
  notifyOnItemDonation: boolean | null;
  silenceClosingTexts: boolean;
  signupDesc: string;
  isHideNameInHistory: boolean;
  reservationsAlt: string;
  sponsorshipsAlt: string;
  hiddenTabs: string | null;
  isMGSponsored: boolean;
  mgSponsorId: number;
  allowToUpdateReservation: boolean;
  askHandicap: boolean;
  maxGolfers: number;
  golfTeamSize: number;
  courseHoles: string;
  teamsPerHole: string;
  scheduleFormat: string;
  scoringFormat: string;
  hideBidNumFromBidders: boolean | null;
  buyersPremPerc: string;
  hideFunds: boolean | null;
  hideTribute: boolean | null;
  disablePartialPayments: boolean | null;
  paymentGateway: string;
  paymentCreds: string | null;
  fundOptions: string;
  fundsAlt: string;
  title: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  feeTypeSetting: number;
  ticketDescription: string;
  ticketDate: string;
  checkInOpens: string | null;
  cocktailHour: string | null;
  dinner: string | null;
  auctionPresentation: string | null;
  eventVenueName: string;
  venueAddress: string;
  venueCity: string;
  venueState: string;
  venueZip: string;
  registrationMode: boolean;
  feeType: number;
  feeName: string;
  feePer: string;
  guestCustomFields: string;
  spoFirst: boolean;
  hideDonation: boolean;
  disabledCardSave: boolean;
  disabledPartnerLink: boolean;
  feeTypeTicket: number;
  mgSponsorLogo: string;
  mgSponsorBackground: string;
  isEventId: boolean;
}

export interface SettingResponse {
  setting: EventSetting;
  themeSettings: ThemeSetting[];
  showMainTab: ShowMainTab;
  sponsor: Sponsor[];
  success: boolean;
}